"""Markdown report generator."""

from __future__ import annotations

from mailtracebox.config.schema import ReportsConfig
from mailtracebox.core.context import Context
from mailtracebox.reports.base import BaseReporter


class MarkdownReporter(BaseReporter):
    @property
    def format_name(self) -> str:
        return "markdown"

    @property
    def file_extension(self) -> str:
        return ".md"

    def generate(self, context: Context, config: ReportsConfig) -> str:
        lines: list[str] = []
        lines.append("# Email Intelligence Report\n")
        lines.append(f"**Target:** `{context.target}`  ")
        lines.append(f"**Scan ID:** `{context.scan_id}`  ")
        lines.append(f"**Started:** {context.started_at.isoformat()}  ")
        if context.completed_at:
            lines.append(f"**Completed:** {context.completed_at.isoformat()}  ")
        if context.duration is not None:
            lines.append(f"**Duration:** {context.duration:.1f}s  ")
        lines.append("")

        emails = _sync_list(context.emails)
        if emails:
            lines.append("## Email Addresses\n")
            lines.append("| Address | Source | Confidence |")
            lines.append("|---------|--------|------------|")
            for e in emails:
                lines.append(f"| `{e.address}` | {e.source or '—'} | {e.confidence:.0%} |")
            lines.append("")

        domains = _sync_list(context.domains)
        if domains:
            lines.append("## Domains\n")
            for d in domains:
                lines.append(f"### {d.domain}\n")
                if d.registrar:
                    lines.append(f"- **Registrar:** {d.registrar}")
                if d.a_records:
                    lines.append(f"- **A Records:** {', '.join(d.a_records)}")
                if d.mx_records:
                    lines.append("- **MX Records:**")
                    for mx in d.mx_records:
                        lines.append(f"  - `{mx.host}` (priority {mx.priority})")
                if d.spf_record:
                    lines.append(f"- **SPF:** `{d.spf_record}`")
                if d.dmarc_record:
                    lines.append(f"- **DMARC:** `{d.dmarc_record}`")
                lines.append("")

        social = _sync_list(context.social_profiles)
        if social:
            lines.append("## Social Profiles\n")
            lines.append("| Platform | Username | URL |")
            lines.append("|----------|----------|-----|")
            for p in social:
                lines.append(f"| {p.platform} | `{p.username}` | [{p.url}]({p.url}) |")
            lines.append("")

        breaches = _sync_list(context.breaches)
        if breaches:
            lines.append("## Data Breaches\n")
            lines.append("| Name | Date | Records | Verified |")
            lines.append("|------|------|---------|----------|")
            for b in breaches:
                date = b.breach_date.strftime("%Y-%m-%d") if b.breach_date else "—"
                count = f"{b.pwn_count:,}" if b.pwn_count else "—"
                verified = "Yes" if b.is_verified else "No"
                lines.append(f"| {b.name} | {date} | {count} | {verified} |")
            lines.append("")

        plugin_results = list(context._plugin_results.values())
        if plugin_results:
            lines.append("## Plugin Execution\n")
            lines.append("| Plugin | Status | Duration | Items |")
            lines.append("|--------|--------|----------|-------|")
            for pr in plugin_results:
                dur = f"{pr.duration_seconds:.2f}s" if pr.duration_seconds else "—"
                lines.append(f"| {pr.plugin_name} | {pr.status.value} | {dur} | {pr.items_found} |")
            lines.append("")

        lines.append("---\nGenerated by mailtracebox\n")
        return "\n".join(lines)


def _sync_list(collection: object) -> list:
    """Extract items from an EntityCollection without await."""
    return list(collection._items.values())  # type: ignore[attr-defined]
